[package]
name = "tempo-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
tempo-timeline = { path = "../tempo-timeline" }
tempo-export = { path = "../tempo-export" }
tracing = { workspace = true }
libc = { workspace = true }
