[package]
name = "tempo-render"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tempo-timeline = { path = "../tempo-timeline" }
tempo-media = { path = "../tempo-media" }
wgpu = { workspace = true }
bytemuck = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
gdk4 = { workspace = true }
gtk4 = { workspace = true }
glib = { workspace = true }
indexmap = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
pollster = { workspace = true }
cairo-rs = { workspace = true }
image = { workspace = true }
