[package]
name = "tempo-media"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tempo-timeline = { path = "../tempo-timeline" }
ffmpeg-next = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
